"""add_session_cookies

Revision ID: 0fb9d7724c92
Revises: e12345678901
Create Date: 2026-01-29 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fb9d7724c92"
down_revision: Union[str, Sequence[str], None] = "e12345678901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if session_cookies table exists, create if not
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if "session_cookies" not in tables:
        op.create_table(
            "session_cookies",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("platform", sa.String(length=50), nullable=False),
            sa.Column("cookies", sa.Text(), nullable=False),
            sa.Column("expires_at", sa.DateTime(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            "idx_session_user_platform",
            "session_cookies",
            ["user_id", "platform"],
            unique=False,
        )
        op.create_index(
            "idx_session_expires", "session_cookies", ["expires_at"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if "session_cookies" in tables:
        op.drop_index("idx_session_expires", table_name="session_cookies")
        op.drop_index("idx_session_user_platform", table_name="session_cookies")
        op.drop_table("session_cookies")
    # ### end Alembic commands ###
