"""add_password_reset_token_to_users

Revision ID: 47efb524293a
Revises: 876db55b7ff1
Create Date: 2025-12-25 00:57:58.612920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47efb524293a'
down_revision: Union[str, Sequence[str], None] = '876db55b7ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'users' in tables:
        users_columns = [col['name'] for col in inspector.get_columns('users')]
        if 'password_reset_token' not in users_columns:
            with op.batch_alter_table('users', schema=None) as batch_op:
                batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
                batch_op.add_column(sa.Column('password_reset_token_expires', sa.DateTime(), nullable=True))
                batch_op.create_index('ix_users_password_reset_token', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if 'users' in op.get_bind().execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='users'")).fetchall():
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_index('ix_users_password_reset_token')
            batch_op.drop_column('password_reset_token_expires')
            batch_op.drop_column('password_reset_token')
    # ### end Alembic commands ###
