"""add_user_id_to_resumes

Revision ID: 876db55b7ff1
Revises: b577e6a51f46
Create Date: 2025-12-25 00:40:22.531124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876db55b7ff1'
down_revision: Union[str, Sequence[str], None] = 'b577e6a51f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist and columns already exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    # Clean up any leftover temp tables
    if '_alembic_tmp_cover_letters' in tables:
        op.drop_table('_alembic_tmp_cover_letters')
    
    # Handle cover_letters foreign key if table exists
    if 'cover_letters' in tables:
        cover_letters_columns = [col['name'] for col in inspector.get_columns('cover_letters')]
        if 'user_id' in cover_letters_columns:
            # Check if foreign key already exists
            fks = inspector.get_foreign_keys('cover_letters')
            fk_names = [fk.get('name') for fk in fks if fk.get('name')]
            if 'fk_cover_letters_user_id' not in fk_names:
                with op.batch_alter_table('cover_letters', schema=None) as batch_op:
                    batch_op.create_foreign_key('fk_cover_letters_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Handle resumes user_id column and foreign key
    if 'resumes' in tables:
        resumes_columns = [col['name'] for col in inspector.get_columns('resumes')]
        if 'user_id' not in resumes_columns:
            with op.batch_alter_table('resumes', schema=None) as batch_op:
                batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
                batch_op.create_foreign_key('fk_resumes_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if 'resumes' in op.get_bind().execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='resumes'")).fetchall():
        with op.batch_alter_table('resumes', schema=None) as batch_op:
            batch_op.drop_constraint('fk_resumes_user_id', type_='foreignkey')
            batch_op.drop_column('user_id')
    
    if 'cover_letters' in op.get_bind().execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='cover_letters'")).fetchall():
        with op.batch_alter_table('cover_letters', schema=None) as batch_op:
            batch_op.drop_constraint('fk_cover_letters_user_id', type_='foreignkey')
    # ### end Alembic commands ###
