"""add_users_and_sessions

Revision ID: b577e6a51f46
Revises: 3842c06f2231
Create Date: 2025-12-25 00:00:06.118704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b577e6a51f46'
down_revision: Union[str, Sequence[str], None] = '3842c06f2231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if users table exists, create if not
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'users' not in tables:
        op.create_table('users',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
        op.create_index('idx_user_email', 'users', ['email'], unique=False)
        op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    if 'user_sessions' not in tables:
        op.create_table('user_sessions',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('user_id', sa.String(), nullable=False),
            sa.Column('refresh_token', sa.String(length=500), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('last_used_at', sa.DateTime(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_session_expires_at', 'user_sessions', ['expires_at'], unique=False)
        op.create_index('idx_session_is_active', 'user_sessions', ['is_active'], unique=False)
        op.create_index('idx_session_refresh_token', 'user_sessions', ['refresh_token'], unique=False)
        op.create_index('idx_session_user_id', 'user_sessions', ['user_id'], unique=False)
        op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    
    # Use batch mode for SQLite to handle foreign key constraints
    # Check if columns already exist before adding
    if 'cover_letters' in tables:
        cover_letters_columns = [col['name'] for col in inspector.get_columns('cover_letters')]
        if 'user_id' not in cover_letters_columns:
            with op.batch_alter_table('cover_letters', schema=None) as batch_op:
                batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
                batch_op.create_foreign_key('fk_cover_letters_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    if 'job_applications' in tables:
        job_applications_columns = [col['name'] for col in inspector.get_columns('job_applications')]
        if 'user_id' not in job_applications_columns:
            with op.batch_alter_table('job_applications', schema=None) as batch_op:
                batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
                batch_op.create_foreign_key('fk_job_applications_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Create indexes only if they don't exist
    existing_indexes = {}
    for table_name in tables:
        existing_indexes[table_name] = [idx['name'] for idx in inspector.get_indexes(table_name)]
    
    # Add missing indexes (check before creating to avoid errors)
    index_operations = [
        ('ai_activities', 'idx_ai_activity_created_at', ['created_at']),
        ('ai_activities', 'idx_ai_activity_success', ['success']),
        ('ai_activities', 'idx_ai_activity_type', ['activity_type']),
        ('ai_activities', 'idx_ai_activity_user_id', ['user_id']),
        ('file_metadata', 'idx_file_metadata_is_active', ['is_active']),
        ('file_metadata', 'idx_file_metadata_md5', ['md5_hash']),
        ('file_metadata', 'idx_file_metadata_path', ['file_path']),
        ('file_metadata', 'idx_file_metadata_type', ['file_type']),
        ('file_metadata', 'idx_file_metadata_uploaded_at', ['uploaded_at']),
        ('job_applications', 'idx_application_applied_date', ['applied_date']),
        ('job_applications', 'idx_application_company', ['company']),
        ('job_applications', 'idx_application_company_status', ['company', 'status']),
        ('job_applications', 'idx_application_created_at', ['created_at']),
        ('job_applications', 'idx_application_follow_up_date', ['follow_up_date']),
        ('job_applications', 'idx_application_resume_id', ['resume_id']),
        ('job_applications', 'idx_application_status', ['status']),
        ('job_applications', 'idx_application_updated_at', ['updated_at']),
        ('job_searches', 'idx_job_search_date', ['search_date']),
        ('job_searches', 'idx_job_search_location', ['location']),
        ('resumes', 'idx_resume_created_at', ['created_at']),
        ('resumes', 'idx_resume_is_default', ['is_default']),
    ]
    
    for table_name, index_name, columns in index_operations:
        if table_name in tables and index_name not in existing_indexes.get(table_name, []):
            try:
                op.create_index(index_name, table_name, columns, unique=False)
            except Exception:
                pass  # Index might already exist with different name
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_applications_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cover_letters_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    
    op.drop_index('idx_resume_is_default', table_name='resumes')
    op.drop_index('idx_resume_created_at', table_name='resumes')
    op.drop_index('idx_job_search_location', table_name='job_searches')
    op.drop_index('idx_job_search_date', table_name='job_searches')
    op.drop_index('idx_application_updated_at', table_name='job_applications')
    op.drop_index('idx_application_status', table_name='job_applications')
    op.drop_index('idx_application_resume_id', table_name='job_applications')
    op.drop_index('idx_application_follow_up_date', table_name='job_applications')
    op.drop_index('idx_application_created_at', table_name='job_applications')
    op.drop_index('idx_application_company_status', table_name='job_applications')
    op.drop_index('idx_application_company', table_name='job_applications')
    op.drop_index('idx_application_applied_date', table_name='job_applications')
    op.drop_index('idx_file_metadata_uploaded_at', table_name='file_metadata')
    op.drop_index('idx_file_metadata_type', table_name='file_metadata')
    op.drop_index('idx_file_metadata_path', table_name='file_metadata')
    op.drop_index('idx_file_metadata_md5', table_name='file_metadata')
    op.drop_index('idx_file_metadata_is_active', table_name='file_metadata')
    op.drop_index('idx_ai_activity_user_id', table_name='ai_activities')
    op.drop_index('idx_ai_activity_type', table_name='ai_activities')
    op.drop_index('idx_ai_activity_success', table_name='ai_activities')
    op.drop_index('idx_ai_activity_created_at', table_name='ai_activities')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index('idx_session_user_id', table_name='user_sessions')
    op.drop_index('idx_session_refresh_token', table_name='user_sessions')
    op.drop_index('idx_session_is_active', table_name='user_sessions')
    op.drop_index('idx_session_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
