"""add_rate_limits_table

Revision ID: c939700876c3
Revises: 4c0fcbbc115f
Create Date: 2026-01-31 15:30:39.545040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c939700876c3'
down_revision: Union[str, Sequence[str], None] = '4c0fcbbc115f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_global_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('active_provider', sa.String(length=50), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('default_max_tokens', sa.Integer(), nullable=False),
    sa.Column('auto_retry_on_failure', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('fallback_to_mock', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_tokens_per_minute', sa.Integer(), nullable=False),
    sa.Column('log_prompts', sa.Boolean(), nullable=False),
    sa.Column('log_responses', sa.Boolean(), nullable=False),
    sa.Column('cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('supports_resume_optimization', sa.Boolean(), nullable=False),
    sa.Column('supports_cover_letter', sa.Boolean(), nullable=False),
    sa.Column('supports_interview_prep', sa.Boolean(), nullable=False),
    sa.Column('supports_career_insights', sa.Boolean(), nullable=False),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('max_requests_daily', sa.Integer(), nullable=True),
    sa.Column('cost_today', sa.Float(), nullable=False),
    sa.Column('max_cost_daily', sa.Float(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_index('idx_ai_provider_enabled', 'ai_provider_configs', ['is_enabled'], unique=False)
    op.create_index('idx_ai_provider_name', 'ai_provider_configs', ['provider_name'], unique=False)
    op.create_index('idx_ai_provider_priority', 'ai_provider_configs', ['priority'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index('idx_alert_rule_metric_enabled', 'alert_rules', ['metric_name', 'enabled'], unique=False)
    op.create_index(op.f('ix_alert_rules_enabled'), 'alert_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_alert_rules_metric_name'), 'alert_rules', ['metric_name'], unique=False)
    op.create_table('auto_apply_activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cycle_id', sa.String(), nullable=True),
    sa.Column('cycle_start', sa.DateTime(), nullable=True),
    sa.Column('cycle_end', sa.DateTime(), nullable=True),
    sa.Column('cycle_status', sa.String(), nullable=False),
    sa.Column('jobs_searched', sa.Integer(), nullable=False),
    sa.Column('jobs_matched', sa.Integer(), nullable=False),
    sa.Column('jobs_applied', sa.Integer(), nullable=False),
    sa.Column('applications_successful', sa.Integer(), nullable=False),
    sa.Column('applications_failed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_created', 'auto_apply_activity_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_cycle', 'auto_apply_activity_logs', ['cycle_id'], unique=False)
    op.create_index('idx_activity_status', 'auto_apply_activity_logs', ['cycle_status'], unique=False)
    op.create_index('idx_activity_user', 'auto_apply_activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_auto_apply_activity_logs_cycle_id'), 'auto_apply_activity_logs', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_auto_apply_activity_logs_cycle_start'), 'auto_apply_activity_logs', ['cycle_start'], unique=False)
    op.create_index(op.f('ix_auto_apply_activity_logs_cycle_status'), 'auto_apply_activity_logs', ['cycle_status'], unique=False)
    op.create_index(op.f('ix_auto_apply_activity_logs_user_id'), 'auto_apply_activity_logs', ['user_id'], unique=False)
    op.create_table('auto_apply_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('search_criteria', sa.Text(), nullable=True),
    sa.Column('max_applications', sa.Integer(), nullable=False),
    sa.Column('apply_schedule', sa.String(), nullable=True),
    sa.Column('schedule_time', sa.String(), nullable=True),
    sa.Column('resume_id', sa.String(), nullable=True),
    sa.Column('cover_letter_preference', sa.String(), nullable=True),
    sa.Column('auto_retry_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_retry_max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auto_apply_enabled', 'auto_apply_configs', ['enabled'], unique=False)
    op.create_index('idx_auto_apply_resume', 'auto_apply_configs', ['resume_id'], unique=False)
    op.create_index('idx_auto_apply_user', 'auto_apply_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_auto_apply_configs_resume_id'), 'auto_apply_configs', ['resume_id'], unique=False)
    op.create_index(op.f('ix_auto_apply_configs_user_id'), 'auto_apply_configs', ['user_id'], unique=False)
    op.create_table('configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configs_key'), 'configs', ['key'], unique=True)
    op.create_index(op.f('ix_configs_name'), 'configs', ['name'], unique=True)
    op.create_table('error_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_created_at', 'error_logs', ['created_at'], unique=False)
    op.create_index('idx_error_type_severity', 'error_logs', ['error_type', 'severity'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_request_path'), 'error_logs', ['request_path'], unique=False)
    op.create_index(op.f('ix_error_logs_severity'), 'error_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_error_logs_user_id'), 'error_logs', ['user_id'], unique=False)
    op.create_table('failure_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('screenshot', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_failure_created', 'failure_logs', ['created_at'], unique=False)
    op.create_index('idx_failure_error_type', 'failure_logs', ['error_type'], unique=False)
    op.create_index('idx_failure_platform', 'failure_logs', ['platform'], unique=False)
    op.create_index('idx_failure_user_task', 'failure_logs', ['user_id', 'task_name'], unique=False)
    op.create_index(op.f('ix_failure_logs_application_id'), 'failure_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_failure_logs_error_type'), 'failure_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_failure_logs_job_id'), 'failure_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_failure_logs_platform'), 'failure_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_failure_logs_task_name'), 'failure_logs', ['task_name'], unique=False)
    op.create_index(op.f('ix_failure_logs_user_id'), 'failure_logs', ['user_id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metric_name_timestamp', 'performance_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_index('idx_metric_timestamp', 'performance_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_performance_metrics_metric_name'), 'performance_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_performance_metrics_timestamp'), 'performance_metrics', ['timestamp'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('applications_count', sa.Integer(), nullable=False),
    sa.Column('hourly_limit', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_count', 'rate_limits', ['applications_count'], unique=False)
    op.create_index('idx_rate_last_reset', 'rate_limits', ['last_reset'], unique=False)
    op.create_index('idx_rate_user_platform', 'rate_limits', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_rate_limits_platform'), 'rate_limits', ['platform'], unique=False)
    op.create_index(op.f('ix_rate_limits_user_id'), 'rate_limits', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    op.create_table('ai_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_activity_created_at', 'ai_activities', ['created_at'], unique=False)
    op.create_index('idx_ai_activity_success', 'ai_activities', ['success'], unique=False)
    op.create_index('idx_ai_activity_type', 'ai_activities', ['activity_type'], unique=False)
    op.create_index('idx_ai_activity_user_id', 'ai_activities', ['user_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_rule_id', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_alert_rule_id'), 'alert_history', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_history_triggered_at'), 'alert_history', ['triggered_at'], unique=False)
    op.create_table('cover_letters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('md5_hash', sa.String(length=32), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('idx_file_metadata_is_active', 'file_metadata', ['is_active'], unique=False)
    op.create_index('idx_file_metadata_md5', 'file_metadata', ['md5_hash'], unique=False)
    op.create_index('idx_file_metadata_path', 'file_metadata', ['file_path'], unique=False)
    op.create_index('idx_file_metadata_type', 'file_metadata', ['file_type'], unique=False)
    op.create_index('idx_file_metadata_uploaded_at', 'file_metadata', ['uploaded_at'], unique=False)
    op.create_index('idx_file_metadata_user_id', 'file_metadata', ['user_id'], unique=False)
    op.create_table('job_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('search_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_search_date', 'job_searches', ['search_date'], unique=False)
    op.create_index('idx_job_search_location', 'job_searches', ['location'], unique=False)
    op.create_index('idx_job_search_user_id', 'job_searches', ['user_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(length=2000), nullable=False),
    sa.Column('p256dh_key', sa.String(length=512), nullable=False),
    sa.Column('auth_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index('idx_push_subscription_created_at', 'push_subscriptions', ['created_at'], unique=False)
    op.create_index('idx_push_subscription_user_id', 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_created_at', 'resumes', ['created_at'], unique=False)
    op.create_index('idx_resume_is_default', 'resumes', ['is_default'], unique=False)
    op.create_table('session_cookies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('cookies', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_expires', 'session_cookies', ['expires_at'], unique=False)
    op.create_index('idx_session_user_platform', 'session_cookies', ['user_id', 'platform'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_is_active', 'user_sessions', ['is_active'], unique=False)
    op.create_index('idx_session_refresh_token', 'user_sessions', ['refresh_token'], unique=False)
    op.create_index('idx_session_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_table('job_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'OFFER_RECEIVED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.Column('cover_letter_path', sa.String(length=500), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=True),
    sa.Column('cover_letter_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_applied_date', 'job_applications', ['applied_date'], unique=False)
    op.create_index('idx_application_company', 'job_applications', ['company'], unique=False)
    op.create_index('idx_application_company_status', 'job_applications', ['company', 'status'], unique=False)
    op.create_index('idx_application_created_at', 'job_applications', ['created_at'], unique=False)
    op.create_index('idx_application_follow_up_date', 'job_applications', ['follow_up_date'], unique=False)
    op.create_index('idx_application_resume_id', 'job_applications', ['resume_id'], unique=False)
    op.create_index('idx_application_status', 'job_applications', ['status'], unique=False)
    op.create_index('idx_application_updated_at', 'job_applications', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_application_updated_at', table_name='job_applications')
    op.drop_index('idx_application_status', table_name='job_applications')
    op.drop_index('idx_application_resume_id', table_name='job_applications')
    op.drop_index('idx_application_follow_up_date', table_name='job_applications')
    op.drop_index('idx_application_created_at', table_name='job_applications')
    op.drop_index('idx_application_company_status', table_name='job_applications')
    op.drop_index('idx_application_company', table_name='job_applications')
    op.drop_index('idx_application_applied_date', table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index('idx_session_user_id', table_name='user_sessions')
    op.drop_index('idx_session_refresh_token', table_name='user_sessions')
    op.drop_index('idx_session_is_active', table_name='user_sessions')
    op.drop_index('idx_session_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_session_user_platform', table_name='session_cookies')
    op.drop_index('idx_session_expires', table_name='session_cookies')
    op.drop_table('session_cookies')
    op.drop_index('idx_resume_is_default', table_name='resumes')
    op.drop_index('idx_resume_created_at', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('idx_push_subscription_user_id', table_name='push_subscriptions')
    op.drop_index('idx_push_subscription_created_at', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_table('password_history')
    op.drop_index('idx_job_search_user_id', table_name='job_searches')
    op.drop_index('idx_job_search_location', table_name='job_searches')
    op.drop_index('idx_job_search_date', table_name='job_searches')
    op.drop_table('job_searches')
    op.drop_index('idx_file_metadata_user_id', table_name='file_metadata')
    op.drop_index('idx_file_metadata_uploaded_at', table_name='file_metadata')
    op.drop_index('idx_file_metadata_type', table_name='file_metadata')
    op.drop_index('idx_file_metadata_path', table_name='file_metadata')
    op.drop_index('idx_file_metadata_md5', table_name='file_metadata')
    op.drop_index('idx_file_metadata_is_active', table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_table('cover_letters')
    op.drop_index(op.f('ix_alert_history_triggered_at'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_rule_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index('idx_ai_activity_user_id', table_name='ai_activities')
    op.drop_index('idx_ai_activity_type', table_name='ai_activities')
    op.drop_index('idx_ai_activity_success', table_name='ai_activities')
    op.drop_index('idx_ai_activity_created_at', table_name='ai_activities')
    op.drop_table('ai_activities')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rate_limits_user_id'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_platform'), table_name='rate_limits')
    op.drop_index('idx_rate_user_platform', table_name='rate_limits')
    op.drop_index('idx_rate_last_reset', table_name='rate_limits')
    op.drop_index('idx_rate_count', table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_performance_metrics_timestamp'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_metric_name'), table_name='performance_metrics')
    op.drop_index('idx_metric_timestamp', table_name='performance_metrics')
    op.drop_index('idx_metric_name_timestamp', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_failure_logs_user_id'), table_name='failure_logs')
    op.drop_index(op.f('ix_failure_logs_task_name'), table_name='failure_logs')
    op.drop_index(op.f('ix_failure_logs_platform'), table_name='failure_logs')
    op.drop_index(op.f('ix_failure_logs_job_id'), table_name='failure_logs')
    op.drop_index(op.f('ix_failure_logs_error_type'), table_name='failure_logs')
    op.drop_index(op.f('ix_failure_logs_application_id'), table_name='failure_logs')
    op.drop_index('idx_failure_user_task', table_name='failure_logs')
    op.drop_index('idx_failure_platform', table_name='failure_logs')
    op.drop_index('idx_failure_error_type', table_name='failure_logs')
    op.drop_index('idx_failure_created', table_name='failure_logs')
    op.drop_table('failure_logs')
    op.drop_index(op.f('ix_error_logs_user_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_severity'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_request_path'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index('idx_error_type_severity', table_name='error_logs')
    op.drop_index('idx_error_created_at', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_configs_name'), table_name='configs')
    op.drop_index(op.f('ix_configs_key'), table_name='configs')
    op.drop_table('configs')
    op.drop_index(op.f('ix_auto_apply_configs_user_id'), table_name='auto_apply_configs')
    op.drop_index(op.f('ix_auto_apply_configs_resume_id'), table_name='auto_apply_configs')
    op.drop_index('idx_auto_apply_user', table_name='auto_apply_configs')
    op.drop_index('idx_auto_apply_resume', table_name='auto_apply_configs')
    op.drop_index('idx_auto_apply_enabled', table_name='auto_apply_configs')
    op.drop_table('auto_apply_configs')
    op.drop_index(op.f('ix_auto_apply_activity_logs_user_id'), table_name='auto_apply_activity_logs')
    op.drop_index(op.f('ix_auto_apply_activity_logs_cycle_status'), table_name='auto_apply_activity_logs')
    op.drop_index(op.f('ix_auto_apply_activity_logs_cycle_start'), table_name='auto_apply_activity_logs')
    op.drop_index(op.f('ix_auto_apply_activity_logs_cycle_id'), table_name='auto_apply_activity_logs')
    op.drop_index('idx_activity_user', table_name='auto_apply_activity_logs')
    op.drop_index('idx_activity_status', table_name='auto_apply_activity_logs')
    op.drop_index('idx_activity_cycle', table_name='auto_apply_activity_logs')
    op.drop_index('idx_activity_created', table_name='auto_apply_activity_logs')
    op.drop_table('auto_apply_activity_logs')
    op.drop_index(op.f('ix_alert_rules_metric_name'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_enabled'), table_name='alert_rules')
    op.drop_index('idx_alert_rule_metric_enabled', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('idx_ai_provider_priority', table_name='ai_provider_configs')
    op.drop_index('idx_ai_provider_name', table_name='ai_provider_configs')
    op.drop_index('idx_ai_provider_enabled', table_name='ai_provider_configs')
    op.drop_table('ai_provider_configs')
    op.drop_table('ai_global_settings')
    # ### end Alembic commands ###
